"""queue_and_status

Revision ID: 135f81851d02
Revises: 26c2ef8ec0c3
Create Date: 2025-06-08 15:25:16.435605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '135f81851d02'
down_revision: Union[str, None] = '26c2ef8ec0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('queued', 'downloading', 'merging', 'uploading_vk', 'uploading_rutube', 'uploading_dzen', 'completed', 'failed', 'deleted', name='taskstatus'),
               nullable=False)
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='userstatus'),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'registered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='userstatus'),
               nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tasks', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('queued', 'downloading', 'merging', 'uploading_vk', 'uploading_rutube', 'uploading_dzen', 'completed', 'failed', 'deleted', name='taskstatus'),
               nullable=True)
    op.alter_column('tasks', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
